### ISSUE TITLE
战地4查询的返回JSON结构有些不一样

### ISSUE THREAD

**Issue by Gaylone** [azmiao/bf_search#1]
战地1/5查询正常，战地4查询报错，我看了一下数据结构里没有对应的字段，望修正一下
![DW(9O(NQ(4B%~%`ATA5RH0R](https://user-images.githubusercontent.com/69965504/131618112-dbbd52ac-a66a-4314-bac0-7ccaf5937d64.png)

**Comment by azmiao** [comment]
23333，我还以为战地4没人玩我就没看Json，我自己没有战地4的号，你有没有返回的json样例可以看看的

**Comment by Gaylone** [comment]
？？？我这现代战争不配有资格
害，你这要啥号，直接一个昵称的事情，给你个昵称，你看看
Gaylone

**Comment by azmiao** [comment]
> ？？？我这现代战争不配有资格
> 害，你这要啥号，直接一个昵称的事情，给你个昵称，你看看
> Gaylone

ok，看到数据了，这就去改2333

**Comment by azmiao** [comment]
搞定了hhh

**Comment by Gaylone** [comment]
爹4遗老表示很失望，下次不能再这样了哦！

**Comment by azmiao** [comment]
> 爹4遗老表示很失望，下次不能再这样了哦！

hhhhh，主要是我的几个朋友要么打1要么5

**Comment by Gaylone** [comment]
咋回事啊大哥？给我整不会了

![9X G2@K$J8US)YH@H6NM0`H](https://user-images.githubusercontent.com/69965504/131628438-e4d9aa7c-b9f9-43af-94c0-6c620163db25.png)

**Comment by azmiao** [comment]
> 咋回事啊大哥？给我整不会了
> 
> ![9X G2@K$J8US)YH@H6NM0`H](https://user-images.githubusercontent.com/69965504/131628438-e4d9aa7c-b9f9-43af-94c0-6c620163db25.png)

啊？为啥我自己的姬器人查你的昵称没问题...我再看看

**Comment by Gaylone** [comment]
我看了一下说你这不能字符串除以字符串呢

**Comment by azmiao** [comment]
> 我看了一下说你这不能字符串除以字符串呢

确实，但我print(type)出来是Int，哎我给他强制转int吧，好怪

**Comment by azmiao** [comment]
你现在再试试？

**Comment by Gaylone** [comment]
可以了
